name: Publish

on:
  repository_dispatch:
    types: [vortex_extension_update]
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.14.0

    - run: npm ci

    - run: npm run build
    
    - uses: actions/upload-artifact@v3
      with:
        name: game-mount-and-blade2
        path: game-mount-and-blade2.7z

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: game-mount-and-blade2

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        body: |
          Download and install using the Extensions pane in Vortex.
          To manually install, extract the 7z to %APPDATA%/Vortex/plugins/game-mount-and-blade2.
        files: |
          ./game-mount-and-blade2.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
