name: Publish

on:
  repository_dispatch:
    types: [vortex_extension_update]
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ master ]

jobs:
  get-package-version:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Get Package Version
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

  get-changelog-info:
    if: github.ref == 'refs/heads/master'
    name: Get Changelog Info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      description: ${{ steps.changelog.outputs.description }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install and Run ChangelogParser
        id: changelog
        run: |
          dotnet tool install -g Bannerlord.ChangelogParser

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

          echo "version=$(bannerlord_changelog_parser latestversion -f "$PWD/changelog.txt")" >> $GITHUB_OUTPUT

          echo "description<<$EOF" >> $GITHUB_OUTPUT
          echo "$(bannerlord_changelog_parser description -f "$PWD/changelog.txt")" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        shell: bash

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.1
        cache: "yarn"

    - run: yarn --frozen-lockfile --immutable --network-timeout 600000 install

    - run: yarn run build
    
    - uses: actions/upload-artifact@v4
      with:
        name: game-mount-and-blade2
        path: dist

  ###########################
  #         GITHUB          #
  ###########################
  publish-on-github:
    if: github.ref == 'refs/heads/master' && needs.get-package-version.outputs.version == needs.get-changelog-info.outputs.version
    needs: [get-package-version, get-changelog-info, build-and-test]
    uses: BUTR/workflows/.github/workflows/release-github.yml@master
    with:
      mod_id: game-mount-and-blade2
      mod_version: ${{ needs.get-changelog-info.outputs.version }}
      mod_description: ${{ needs.get-changelog-info.outputs.description }}
      artifact_name: game-mount-and-blade2

  ###########################
  #        NEXUSMODS        #
  ###########################
  publish-on-nexusmods:
    if: github.ref == 'refs/heads/master' && needs.get-package-version.outputs.version == needs.get-changelog-info.outputs.version
    needs: [get-package-version, get-changelog-info, build-and-test]
    uses: BUTR/workflows/.github/workflows/release-nexusmods.yml@master
    with:
      nexusmods_game_id: site
      nexusmods_mod_id: 875
      mod_filename: game-mount-and-blade2
      mod_version: ${{ needs.get-changelog-info.outputs.version }}
      mod_description: ${{ needs.get-changelog-info.outputs.description }}
      artifact_name: game-mount-and-blade2
      append_v_to_version: false
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.ARAGAS_NEXUSMODS_API_KEY }}
      NEXUSMODS_SESSION_COOKIE: ${{ secrets.ARAGAS_NEXUSMODS_SESSION_COOKIE }}
