name: Publish

on:
  repository_dispatch:
    types: [vortex_extension_update]
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  get-changelog:
    name: Get Changelog
    runs-on: ubuntu-latest
    outputs:
      mod_version: ${{ steps.changelog.outputs.mod_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install and Run ChangelogParser
        id: changelog
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "mod_version=${VERSION:1}" >> $GITHUB_OUTPUT
        shell: bash

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.1
        cache: "yarn"

    - run: yarn --frozen-lockfile --immutable --network-timeout 600000 install

    - run: yarn run build
    
    - uses: actions/upload-artifact@v4
      with:
        name: game-mount-and-blade2
        path: game-mount-and-blade2.7z

  ###########################
  #         GITHUB          #
  ###########################
  publish-on-github:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [get-changelog, build-and-test]
    uses: BUTR/workflows/.github/workflows/release-github.yml@master
    with:
      mod_id: Vortex-Extension
      mod_version: ${{ needs.get-changelog.outputs.mod_version }}
      mod_description: |
          Download and install using the Extensions panel in Vortex.
          To manually install, extract the 7z to %APPDATA%/Vortex/plugins/game-mount-and-blade2.
      artifact_name: game-mount-and-blade2

  ###########################
  #        NEXUSMODS        #
  ###########################
  publish-on-nexusmods:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [get-changelog, build-and-test]
    uses: BUTR/workflows/.github/workflows/release-nexusmods.yml@master
    with:
      nexusmods_game_id: site
      nexusmods_mod_id: 875
      mod_filename: 'Vortex Extension'
      mod_version: ${{ needs.get-changelog.outputs.mod_version }}
      mod_description: |
          Download and install using the Extensions panel in Vortex.
          To manually install, extract the 7z to %APPDATA%/Vortex/plugins/game-mount-and-blade2.
      artifact_name: game-mount-and-blade2
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.ARAGAS_NEXUSMODS_API_KEY }}
      NEXUSMODS_COOKIES: ${{ secrets.ARAGAS_NEXUSMODS_COOKIE_SID_DEVELOP }}
