name: Publish

on:
  repository_dispatch:
    types: [vortex_extension_update]
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ master ]

jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get Version
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.1
        cache: "yarn"

    - run: yarn --frozen-lockfile --immutable --network-timeout 600000 install

    - run: yarn run build
    
    - uses: actions/upload-artifact@v4
      with:
        name: game-mount-and-blade2
        path: dist

  ###########################
  #         GITHUB          #
  ###########################
  publish-on-github:
    if: github.ref == 'refs/heads/master'
    needs: [get-version, build-and-test]
    uses: BUTR/workflows/.github/workflows/release-github.yml@master
    with:
      mod_id: game-mount-and-blade2
      mod_version: ${{ needs.get-version.outputs.version }}
      mod_description: |
          Download and install using the Extensions panel in Vortex.
          To manually install, extract the 7z to %APPDATA%/Vortex/plugins/game-mount-and-blade2.
      artifact_name: game-mount-and-blade2

  ###########################
  #        NEXUSMODS        #
  ###########################
  publish-on-nexusmods:
    if: github.ref == 'refs/heads/master'
    needs: [get-version, build-and-test]
    uses: BUTR/workflows/.github/workflows/release-nexusmods.yml@master
    with:
      nexusmods_game_id: site
      nexusmods_mod_id: 875
      mod_filename: game-mount-and-blade2
      mod_version: ${{ needs.get-version.outputs.version }}
      mod_description: |
          Download and install using the Extensions panel in Vortex.
          To manually install, extract the 7z to %APPDATA%/Vortex/plugins/game-mount-and-blade2.
      artifact_name: game-mount-and-blade2
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.ARAGAS_NEXUSMODS_API_KEY }}
      NEXUSMODS_SESSION_COOKIE: ${{ secrets.ARAGAS_NEXUSMODS_SESSION_COOKIE }}
